name: Pull and Push sygi/whisper-cpp

on:
  workflow_dispatch:

jobs:
  pull-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull sygi/whisper-cpp:cpu-small
        run: |
          docker pull sygi/whisper-cpp:cpu-small

      - name: Tag for GHCR
        run: |
          docker tag sygi/whisper-cpp:cpu-small ghcr.io/wuyayun8/whisper-cpp:cpu-small

      - name: Push to GHCR
        run: |
          docker push ghcr.io/wuyayun8/whisper-cpp:cpu-small
